<%@ page language="java" contentType="text/html; charset=UTF-8"%>
<%@ include file="/inc/taglib.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>网站后台登录</title>
<link href="${basePath }/include/css/bootstrap.min.css" rel="stylesheet">
<link href="${basePath }/include/css/jquery-ui.css" rel="stylesheet">
<script src="${basePath }/include/js/jquery-1.10.2.js"></script>
<script src="${basePath }/include/js/jquery-ui.js"></script>
<script src="${basePath }/include/js/jquery.validate.js"></script>
<script src="${basePath }/include/js/messages_zh.js"></script>
<script type="text/javascript">
function changeImg(id){ 
	   $("#"+id).attr("src","${basePath}/checkCode/getRegisterImage?num="+Math.random());
 }
function ifPass(){
	var flag=$("#select01").attr("disabled");
	if(flag=='disabled'){
		$("#select01").attr("disabled",false);
		$("#select01").attr("name","keepTime");
	}else{
		$("#select01").attr("disabled",true);
		$("#select01").attr("name","");
	}
}

function doSub(){
	$("#nameMsg").html("");
	$("#passMsg").html("");
	$.ajax({
		type: "POST",
		url:"${basePath}/user/login",
		data:$('#form1').serialize(),
	    error: function(request) {
	    	alert("系统错误,请刷新后重试");
	    },
	    success: function(res) {
	    	if(res.code=="1"){
	    	    showMsgParent(res.msg);
	    	}else if(res.code=="2"){
	    		$("#nameMsg").html(res.msg);
	    	}else if(res.code=="3"){
	    		window.location.href="${basePath}/admin/index2.jsp";
	    	}else if(res.code=="4"){
	    		$("#passMsg").html(res.msg);
	    	}else{
	    		showMsgParent(res.msg);
	    	}
	    }
	});

}

function doReset(id){
	document.getElementById(id).reset(); 
	$("#select01").attr("disabled",true);
	$("#select01").attr("name","");
}

function getCookie(name) 
{ 
    var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");
    if(arr=document.cookie.match(reg))
        return unescape(arr[2]); 
    else 
        return null; 
} 

</script>
</head>
<body id="top">
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<p class="brand">NSParenting后台入口</p>
				<div class="nav-collapse collapse" id="main-menu" >
					<ul class="nav" style="width:560px">
						<li style="width:430px">&nbsp;</li>
						<li><a class="dropdown-toggle" href="${basePath}/">返回网站首页</a></li>
					</ul>
				</div>
			</div>
		</div>    
	</div>  
	<div class="container contentflux" style="padding-top:70px;margin-top:50px;">
		<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
		<div class="row" style="width:800px;margin:auto;">
			<div class="span10">
				<form id="form1" class="form-horizontal well" action="" method="post">
					<fieldset>
						<legend style="padding-left:60px;"><b style="font-size: 20px;">用户登录</b></legend>
						<div class="control-group">
							<label class="control-label" for="input01">用户名:</label>
							<div class="controls">
								<input class="input-xlarge" id="userId" name="userCode" value="${userCode }" required type="text">
								<span style="color: red;" id="nameMsg"></span>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="input01">密码:</label>
							<div class="controls"> 
								<input class="input-xlarge" id="passwd" name="password" value="${password }" type="password" required>
								<span style="color: red;" id="passMsg"></span>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="input01">验证码:</label>
							<div class="controls">
								<input class="input-xlarge" style="width:80px;" id="checkCode" name="checkCode" type="text" required minlength="4" maxlength="4"> 
								<img id="topImg" alt="点击更换图片" src="${basePath}/checkCode/getRegisterImage" style="vertical-align:middle;margin-left:20px;width:80px;height:25px;" onclick="changeImg('topImg')">
							</div>
						</div>
						<div class="control-group">
							<div class="controls">
								<label class="checkbox"> 
								<input type="checkbox" id="isRemberPass" name="isRemberPass" value="rember" onclick="ifPass()" <c:if test="${isRemberPass eq 'rember'}">checked</c:if>> 是否记住密码
								</label>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="select01">密码记录时间</label>
							<div class="controls">
								<select id="select01" <c:if test="${empty keepTime}">disabled</c:if> <c:if test="${not empty keepTime}">name="keepTime"</c:if>>
									<option value="86400" <c:if test="${keepTime eq '86400'}">selected</c:if> >一天</option>
									<option value="604800" <c:if test="${keepTime eq '604800'}">selected</c:if> >一周</option>
									<option value="2592000" <c:if test="${keepTime eq '2592000'}">selected</c:if> >一个月</option>
								</select> 
							</div>
						</div>
						<div class="form-actions">
				            <button type="button" class="btn btn-primary" onclick="doSub()">登录</button>
				            <button type="button" class="btn" onclick="doReset('form1')">清空</button>
				        </div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
  <!-- 页面拖拽后，出现返回顶部按钮 -->
	<div class="scrollToTop" id="scroll" style="display:none;">
		回到顶部
	</div>
<script type="text/javascript">
	(function() {
		// use custom tooltip; disable animations for now to work around lack of refresh method on tooltip
		$("#form1").tooltip({
			show: false,
			hide: false
		});
		// validate the comment form when it is submitted
		$("#form1").validate({
			showErrors: function(map, list) {
				// there's probably a way to simplify this
				var focussed = document.activeElement;
				if (focussed && $(focussed).is("input, textarea")) {
					$(this.currentForm).tooltip("close", {
						currentTarget: focussed
					}, true)
				}
				this.currentElements.removeAttr("title").removeClass("ui-state-highlight");
				$.each(list, function(index, error) {
					$(error.element).attr("title", error.message).addClass("ui-state-highlight");
				});
				if (focussed && $(focussed).is("input, textarea")) {
					$(this.currentForm).tooltip("open", {
						target: focussed
					});
				}
			}
		});
	})();
	
	var isRemberPass=getCookie("isRemberPass");
	var reqCookie="${isRemberPass}";
	if(isRemberPass!=null&&isRemberPass!=''&&reqCookie==''){
		$("#userId").val(getCookie("userId"));	
		$("#passwd").val(getCookie("passwd"));	
		$("#isRemberPass").attr("checked",true);
		$("#select01").attr("disabled",false);
		$("#select01").attr("name","keepTime");
		$("#select01").attr("value",getCookie("keepTime"));
	}
</script>
<jsp:include page="/inc/ShowMsg.jsp" flush="true"></jsp:include>	
</body>
</html>
